### ISSUE TITLE
ssdb之类的对比

### ISSUE THREAD

**Issue by bingyupj** [Qihoo360/huststore#1]
可否说下适用场景，比如为什么不用redis,为什么不用ssdb的对比分析？

**Comment by thinkwing** [comment]
这个问题问的好，关注。。。

**Comment by HustXrb** [comment]
你好，对于存储层，huststore主要应用于大数据，内存有限，且对性能有要求的业务；fastdb是huststore存储层最主要创新点，实现高效的查询及版本控制。
与ssdb不同，除协议（huststore使用http）外，使用fastdb优化leveldb，并且，加入mdb缓存kv键值；所以，写操作&随机读操作的性能，会优于ssdb。
分布式消息队列，在高并发大量数据写入消息队列时，写操作优化尤为重要，leveldb会在writebuffer写满时阻塞写操作，然而，fastdb的contentdb模块可以很好的解决这个问题，保证高并发&高性能。
感谢关注huststore。

PS：huststore支持分布式KV存储&分布式消息队列，通过HA（网络&集群的创新点）保证高可用。
