### ISSUE TITLE
对你们系统有几个问题？求解答

### ISSUE THREAD

**Issue by imotai** [Qihoo360/huststore#2]
不好意思，读代码能力较差，所以只能提issue问问题了
* 你们的fastdb开源了么？它的存储模型里数据是有序的还是无序的啊
* 消息队列是怎么实现的，我看你们说支持hash 和 set 感觉这两种存储结构并不是适合消息队列？

**Comment by HustXrb** [comment]
你好，fastdb已开源（hustdb/db/server/module/kv）；fastdb是huststore的创新点之一，实现高效的查询及版本控制，并且，有效优化leveldb的性能；fastdb不对数据排序；
消息队列可以参考hustmq的api，有较为详细的介绍。
感谢关注huststore。

分布式KV存储 = HA（hustdb ha） + DB（hustdb）
分布式消息队列 = HA（hustmq ha） + DB（hustdb）
