### ISSUE TITLE
安装写的不清晰，文档也不好！！！！ 感觉不清晰，这样让人感觉不好

### ISSUE THREAD

**Issue by anthonyyuan** [Qihoo360/huststore#3]

**Comment by jobs-github** [comment]
您好，

部署的相关文档可以参考如下：
https://github.com/Qihoo360/huststore/blob/master/hustdb/doc/doc/guide/hustdb.md
https://github.com/Qihoo360/huststore/blob/master/hustdb/doc/doc/guide/ha.md
https://github.com/Qihoo360/huststore/blob/master/hustmq/doc/doc/guide/hustmq.md
https://github.com/Qihoo360/huststore/blob/master/hustmq/doc/doc/guide/ha.md
以上是"hello world"式的部署，按照步骤操作就可以把服务跑起来，并看到实际效果。

如果您需要了解更加详细的部署以及配置细节，可以参考如下链接：
https://github.com/Qihoo360/huststore/blob/master/hustdb/doc/doc/advanced/hustdb/deploy.md
https://github.com/Qihoo360/huststore/blob/master/hustdb/doc/doc/advanced/ha/deploy.md
https://github.com/Qihoo360/huststore/blob/master/hustdb/doc/doc/advanced/ha/nginx.md
https://github.com/Qihoo360/huststore/blob/master/hustdb/doc/doc/advanced/ha/table.md
https://github.com/Qihoo360/huststore/blob/master/hustdb/doc/doc/advanced/ha/zlog.md
https://github.com/Qihoo360/huststore/blob/master/hustmq/doc/doc/advanced/ha/deploy.md
https://github.com/Qihoo360/huststore/blob/master/hustmq/doc/doc/advanced/ha/nginx.md

关于文档的质量，项目的首页有详细文档的链接，可能您没有留意到这一块内容，这应该是首页设计出了问题，我们会改进，欢迎提供更加具体的建议 ^_^

![doc](https://cloud.githubusercontent.com/assets/3899589/15460927/f906ab4a-20e8-11e6-91d3-3e655cbb0beb.PNG)

为了方便解决您的问题，您可以直接通过如下两个链接看到详细的文档：
hustdb文档：https://github.com/Qihoo360/huststore/blob/master/hustdb/doc/doc/index.md
hustmq文档：https://github.com/Qihoo360/huststore/blob/master/hustmq/doc/doc/index.md

因为项目比较庞大，而人手有限，所以文档的质量我们很难做到Elastic Search、nginx的文档 那么优秀
（人家基本是一个公司几百号人的团队在做，这个我们没法比），
我们只能尽可能把文档做的足够详细（可以参考 Contributors，所有的代码和文档基本就这点人在做），
有不足之处还请多提宝贵意见 ^_^

希望以上的回答能解决您的问题，感谢 ^_^
