### ISSUE TITLE
由此可见，国外这些软件也仅仅是能用而已。

### ISSUE THREAD

**Issue by 12sxa** [Qihoo360/huststore#4]

**Comment by jobs-github** [comment]
您好，

您提到的国外的软件，不知道是否针对上一个 issue 中提到的 elastic search, nginx ? 如果是，我们给出的参考意见是，这两个例子都是极其伟大的开源作品，基本上在各自的领域已经成为事实上的工业标准之一（尤其是 nginx），所以如果您觉得这样的作品 “**也仅仅是能用而已**” ，我们表示难以苟同，但我们依然誓死捍卫您表达的权力 ^_^

如果您对 huststore 的设计、实现或者文档有任何 **可操作性** 的改进意见，欢迎提出来，我们会持续改进。

PS: huststore 不是外国人写的，是中国人写的（当然，我们是站在巨人的肩膀上，比如 leveldb, nginx）

感谢您的关注 ^_^

**Comment by 12sxa** [comment]
首先请不要对号入座，该吐槽仅仅是支持下国产软件，我所指的国外软件并未点名，请不要联想。

发自我的 iPhone
