### ISSUE TITLE
huststore 跟 pika的区别

### ISSUE THREAD

**Issue by wangmang** [Qihoo360/huststore#7]
同样是kv存储， huststore基于leveldb， pika基于rocksdb。
同样都是360的。
huststore和pika有什么区别？
是有不同的适用场景么？
为什么搞两套？

**Comment by jobs-github** [comment]
您好，首先感谢您关注 huststore 项目。以下是 huststore 和 pika 的主要区别：  
1. 存储方面，huststore差异性在于自主研发的 **fastdb**，其设计原理完全不同于已有的存储引擎；  
2. 网络方面，huststore**有独立的ha模块**（nginx模块），因此天然具备nginx所有的优点（高可用，高并发，平滑升级，等等）；  
3. 架构设计方面，huststore由于有独立的ha，支持集群式部署（不是传统的master-slave或master-master，是**真正的分布式系统**），不存在单点限制。  
4. 功能方面，huststore既可以当存储服务使用，也可以作为**消息队列**服务使用（参考hustmq相关的内容）。pika则是用来公司内部替代redis的缓存服务。    

简单点说，如果你希望你的服务支持分布式，用huststore吧，打个广告 ^_^  

ps: 为什么搞两套？因为是不同的团队做的，好了，只能透露这么多了。。。

希望以上的回答对你有用。

**Comment by wangmang** [comment]
好的，多谢多谢^^
