### ISSUE TITLE
文档原理部分能否详细解释下（尤其是架构图部分），谢谢！

### ISSUE THREAD

**Issue by liyongming1982** [Qihoo360/huststore#9]
https://github.com/Qihoo360/huststore/blob/master/res/hustdb.png

**Comment by liyongming1982** [comment]
另：这个系统适合保存文件吗，如100M的二进制文件等

**Comment by jobs-github** [comment]
huststore适合存中小型的kv数据，参考性能测试结果。100M大数据建议存网盘或者专用的ftp
